#!/bin/bash
export DATABASE_CONNECTION_TYPE=postgres
export DATABASE_CONNECTION_USERNAME=foo
export DATABASE_CONNECTION_PASSWORD=foo
export DATABASE_CONNECTION_HOST=foo
export DATABASE_CONNECTION_PORT=5432
export DATABASE_CONNECTION_DATABASE=foo_prod
export DATABASE_QUERY_LOGGING=false

export GUIDESTAR_ESSENTIALS_KEY=foo
export GUIDESTAR_PREMIER_KEY=foo

ts-node ./seedSelectCharities.ts
